title: Viraj Desai
logo: /assets/img/Photo_Viraj_Desai.png
description: Hi, there My name is Viraj Desai. By profession I am a chemical process engineer / process modelling engineer.
show_downloads: true
theme: jekyll-theme-tactile
